// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWViWWv_h1Rtd4uYtvVbB6rcR99LDhaKg',
    appId: '1:1001634176109:web:d81a46a058aa272f2ef364',
    messagingSenderId: '1001634176109',
    projectId: 'mervat-app',
    authDomain: 'mervat-app.firebaseapp.com',
    storageBucket: 'mervat-app.appspot.com',
    measurementId: 'G-8RJNQ1XGTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1LZNqORGRIj7Fo0oKHSRbyGwqZeqQJy0',
    appId: '1:1001634176109:android:5ed62476ff86b7272ef364',
    messagingSenderId: '1001634176109',
    projectId: 'mervat-app',
    storageBucket: 'mervat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5BAfbOK9xq3BnZ9Sdrzn-3UG834Zwxm0',
    appId: '1:1001634176109:ios:f637972794e721112ef364',
    messagingSenderId: '1001634176109',
    projectId: 'mervat-app',
    storageBucket: 'mervat-app.appspot.com',
    iosBundleId: 'com.example.sibawayhWorldKids',
  );
}
