// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDjQGywkv0c2vl9_D7p6mYlTlVzAU4bBo',
    appId: '1:93441299141:web:5f9c880dc3720e6fa2d6ac',
    messagingSenderId: '93441299141',
    projectId: 'test-61e36',
    authDomain: 'test-61e36.firebaseapp.com',
    storageBucket: 'test-61e36.appspot.com',
    measurementId: 'G-0QBM1DEN1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqrSBinAklLtX1UivmPJx6D6bAZJiWUJg',
    appId: '1:93441299141:android:fb8aa2529429850aa2d6ac',
    messagingSenderId: '93441299141',
    projectId: 'test-61e36',
    storageBucket: 'test-61e36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4yW8zRW5DrGfM6C2WTXcwtnI2oGmwun8',
    appId: '1:93441299141:ios:d447602672362590a2d6ac',
    messagingSenderId: '93441299141',
    projectId: 'test-61e36',
    storageBucket: 'test-61e36.appspot.com',
    iosBundleId: 'com.example.sibawayhWorldKids',
  );
}
